[package]
name = "darkwebb-primitives"
version = "0.1.0"
authors = ["Drew Stone <drewstone329@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frame-system = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.7" }
frame-support = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.7" }
sp-std = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.7" }

# Arkworks
ark-ff = { version = "^0.3.0", default-features = false }
ark-ec = { version = "^0.3.0", default-features = false }
ark-std = { version = "^0.3.0", default-features = false }
ark-relations = { version = "^0.3.0", default-features = false }
ark-serialize = { version = "^0.3.0", default-features = false, features = [ "derive" ] }
ark-bls12-381 = { version = "^0.3.0", default-features = false, features = [ "curve" ], optional = true }
ark-bls12-377 = { version = "^0.3.0", default-features = false, features = [ "curve", "r1cs" ], optional = true }
tracing = { version = "0.1", default-features = false, features = [ "attributes" ], optional = true }

blake2 = { version = "0.9", default-features = false }
digest = "0.9"

ark-crypto-primitives = { version = "^0.3.0", features = ["r1cs"], default-features = false }
arkworks-gadgets = { git = "https://github.com/webb-tools/arkworks-gadgets.git", branch = "parameter-decode", default-features = false, optional = true}

[dependencies.codec]
default-features = false
features = ["derive"]
package = "parity-scale-codec"
version = "2.0.0"

[features]
default = ["std", "hashing"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"sp-std/std",
	"ark-ff/std",
	"ark-ec/std",
	"ark-std/std",
	"ark-relations/std"
]
hashing = [
	"arkworks-gadgets",
	"ark-bls12-381",
	"ark-bls12-377",
]
verifying = [
	"arkworks-gadgets",
	"ark-bls12-381",
	"ark-bls12-377",
]